"""empty message

Revision ID: cc92e5ccadda
Revises: 7957ed7615fc
Create Date: 2020-07-01 19:36:14.942267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc92e5ccadda'
down_revision = '7957ed7615fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movie', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actor', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
